# Set up GCC paths
find_program(GXX_COMPILER "g++-8")
if (NOT GXX_COMPILER AND EXISTS "/hpc/base/ctt/packages/compiler/gnu/8.2.0/bin/g++")
    set(GXX_COMPILER "/hpc/base/ctt/packages/compiler/gnu/8.2.0/bin/g++")
endif ()
if (NOT GXX_COMPILER)
    find_program(GXX_COMPILER "g++")
endif ()
find_program(GCC_COMPILER "gcc-8")
if (NOT GCC_COMPILER AND EXISTS "/hpc/base/ctt/packages/compiler/gnu/8.2.0/bin/gcc")
    set(GCC_COMPILER "/hpc/base/ctt/packages/compiler/gnu/8.2.0/bin/gcc")
endif ()
if (NOT GCC_COMPILER)
    find_program(GCC_COMPILER "gcc")
endif ()
find_program(GFC_COMPILER "gfortran-8")
if (NOT GFC_COMPILER AND EXISTS "/hpc/base/ctt/packages/compiler/gnu/8.2.0/bin/gfortran")
    set(GFC_COMPILER "/hpc/base/ctt/packages/compiler/gnu/8.2.0/bin/gfortran")
endif ()
if (NOT GFC_COMPILER)
    find_program(GFC_COMPILER "gfortran")
endif ()
message(STATUS "GCC compiler: ${GCC_COMPILER}")
message(STATUS "GXX compiler: ${GXX_COMPILER}")
message(STATUS "GFC compiler: ${GFC_COMPILER}")

# Set up GCC
set(CMAKE_C_COMPILER "${GCC_COMPILER}")
set(CMAKE_CXX_COMPILER "${GXX_COMPILER}")
set(CMAKE_Fortran_COMPILER "${GFC_COMPILER}")
