version: "3.4"
services:
  energymanager:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: "unless-stopped"
    ports:
      - "2222:22"
    volumes:
      - "./:/EnergyManager"
      - "/mnt/54677e5c-47a2-4c09-b0f6-953df15410d0/UvA/Scriptie/Benchmark/rodinia_3.1:/applications/rodinia"
      - "/mnt/54677e5c-47a2-4c09-b0f6-953df15410d0/UvA/Scriptie/Benchmark/NVIDIA-developer-blog:/applications/nvidia-developer-blog"
      - "/mnt/54677e5c-47a2-4c09-b0f6-953df15410d0/UvA/Scriptie/Benchmark/Jacobi/CudaJacobi:/applications/jacobi"
  energymanager-visualizer:
    build:
      context: "."
      dockerfile: "./Visualizer/Dockerfile"
    restart: "unless-stopped"
    ports:
      - "8888:8888"
    volumes:
      - "./:/EnergyManager"
