version: "3.4"
services:
  energymanager:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: "unless-stopped"
    volumes:
      - "./:/EnergyManager"
  energymanager-visualizer:
    build:
      context: "."
      dockerfile: "./Visualizer/Dockerfile"
    restart: "unless-stopped"
    ports:
      - "8888:8888"
    volumes:
      - "./:/EnergyManager"